services:
  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ~/postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - fosku-network
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${POSTGRES_USER}  
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD} 
      PGADMIN_LISTEN_PORT: ${PGADMIN_DEF_PORT}
    ports:
      - ${PGADMIN_PORT_MAPPING}
    networks:
      - fosku-network
  server:
    image: fosku-server
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "80:8080"
    depends_on:
      - db
    entrypoint: ["sh", "-c", "dotnet ef database update && dotnet fosku-server.dll"]
    networks:
      - fosku-network

networks:
  fosku-network:
    driver: bridge
